### PR TITLE
Spanish Language & more

### PR DESCRIPTION
**Pull request by deeprobin**
Added spanish language, improved some javadoc and added at the onEnable method in main a message for supporting the repository

### CODE REVIEW

**Comment by DeepRobin** [comment]
#push

**Review by heisluft — CHANGES_REQUESTED** [review]
Thank you for your contribution. There are a few inconsitencies in your documentation, please update the respective lines so your pr can get merged.

**Comment by DeepRobin** [comment]
Applied requested changes.

**Comment by DeepRobin** [comment]
#push

**Pull request merged**
